### ISSUE TITLE
Help config

### ISSUE THREAD

**Issue by iulian12h** [tapnisu/forwarding-discord-telegram#258]
I am not familiar with discord naming scheme, how can i make the bot to read only one channel from only one discord group
<img width="916" alt="Screenshot 2024-02-22 183638" src="https://github.com/tapnisu/forwarding-discord-telegram/assets/28490656/8a73d614-d007-4fd4-9790-f9fa491d5f24">

**Comment by tapnisu** [comment]
Oh, hello. Yes, they are called channels.

So, in `config.json` file you should add your [channel ID](https://turbofuture.com/internet/Discord-Channel-ID) to `allowedChannelsIds`. Your `config.json` file should like something like this:

```json
{
  "outputChannels": [],
  "mutedGuildsIds": [],
  "allowedGuildsIds": [],
  "mutedChannelsIds": [],
  "allowedChannelsIds": ["1142046665994408036"],
  "allowedUsersIds": [],
  "mutedUsersIds": [],
  "channelConfigs": {},
  "disableLinkPreview": false,
  "imagesAsMedia": true,
  "showDate": true,
  "showChat": true,
  "stackMessages": false
}
```

> Don't forget to use your channel ID

**Comment by iulian12h** [comment]
A follow up, I am getting this error when i try to build the project

`ubuntu@ip-172-31-38-154:~/forwarding-discord-telegram$ npm run build

> forwarding-discord-telegram@2.1.0 build
> tsc

/home/ubuntu/forwarding-discord-telegram/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/forwarding-discord-telegram/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)`

**Comment by tapnisu** [comment]
Which version of node are you using?

(Forwarding Discord Telegram requires at least version 16)

**Comment by iulian12h** [comment]
v12.22.9

if wrong version how do i upgrade on ubuntu

**Comment by iulian12h** [comment]
Ok i have not v20

**Comment by tapnisu** [comment]
> v12.22.9
> 
> if wrong version how do i upgrade on ubuntu

You can use [NVM](https://github.com/nvm-sh/nvm)

**Comment by tapnisu** [comment]
Everything worked out?

**Comment by iulian12h** [comment]
yes
