### ISSUE TITLE
[Docker] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by Freekers** [tapnisu/forwarding-discord-telegram#360]
Hi there,

Looks like https://github.com/tapnisu/forwarding-discord-telegram/commit/1ace45f684a46c1328632fd6157efcf9d36181d4 broke the Docker image. It crashes after logging in to the account:

```
! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.12.3.tgz
> forwarding-discord-telegram@2.2.2 start /app
> node .
Logged in as XXXXXXXX!
/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/core/error.js:47
    return new GrammyError(`Call to '${method}' failed!`, err, method, payload);
      
           ^
GrammyError: Call to 'getUpdates' failed! (409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running)
    at toGrammyError (/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/core/error.js:47:12)
    at ApiClient.callApi (/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/core/client.js:97:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SenderBot.fetchUpdates (/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/bot.js:422:27)
    at async SenderBot.loop (/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/bot.js:393:33)
    at async SenderBot.start (/app/node_modules/.pnpm/grammy@1.31.3/node_modules/grammy/out/bot.js:314:9) {
  method: 'getUpdates',
  payload: { offset: 1, limit: undefined, timeout: 30, allowed_updates: [] },
      
  ok: false,
  error_code: 409,
  description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {}
}
Node.js v18.20.4
 ELIFECYCLE  Command failed with exit code 1.
```

The last working Docker image version is tapnisu/forwarding-discord-telegram:sha-d318a35

Kind regards

**Comment by tapnisu** [comment]
Hello, thank you for submitting your issue.
Fixed in https://github.com/tapnisu/forwarding-discord-telegram/commit/b04e7f6f59127fa910b0ea21e0c98b6e2842953b.

**Comment by Freekers** [comment]
Thanks for the quick fix. I hereby confirm that https://github.com/tapnisu/forwarding-discord-telegram/commit/b04e7f6f59127fa910b0ea21e0c98b6e2842953b has fixed the issue.

Thank you
